### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [schollz/sdees#23]
Would you please consider creating a LICENSE file containing your copyright information and the text of the MIT license?  The MIT license specifically states that the text of the license must accompany the source code.  (It also makes life easier for people like me who like to package up software like yours for LInux distributions.)

Thanks!

**Comment by schollz** [comment]
Done! https://github.com/schollz/sdees/commit/ddfb13e8b3987d242e9f4dcad19350b1cd67559c
