### ISSUE TITLE
Remove single entries from document

### ISSUE THREAD

**Issue by xori** [schollz/sdees#29]
When I run `sdees -a` and edit an existing line it doesn't save my changes.

https://youtu.be/k8fX4uA4QMk

**Comment by schollz** [comment]
Thanks! I appreciate the video :+1: 

So this isn't really a bug, but more of a missing feature. 

Currently there is no way to delete a single entry in a document (except by removing the entry file from local and remote manually).

Consider it on the todo list!

**Comment by schollz** [comment]
This can be done now with version 2.0 using `--delete`
